name: Publish

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      msg:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Publish
        run: cargo publish --token=${{secrets.CARGO_TOKEN}}
